// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlLG9k4gj_QSNiYMBB7KZAK-jB2tUYFiE',
    appId: '1:411581975774:web:13671755dbbe1c82a5064f',
    messagingSenderId: '411581975774',
    projectId: 'fit-pro-37183',
    authDomain: 'fit-pro-37183.firebaseapp.com',
    storageBucket: 'fit-pro-37183.appspot.com',
    measurementId: 'G-GERCTGPRRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLmqdRpjMmqGBiDQhtj65bVaLtqVld2_E',
    appId: '1:411581975774:android:21c895c3314ca8b3a5064f',
    messagingSenderId: '411581975774',
    projectId: 'fit-pro-37183',
    storageBucket: 'fit-pro-37183.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSfy8vE21FozMJOx5Hwx7ajbihVe526RI',
    appId: '1:411581975774:ios:19438bb30e765bf8a5064f',
    messagingSenderId: '411581975774',
    projectId: 'fit-pro-37183',
    storageBucket: 'fit-pro-37183.appspot.com',
    iosBundleId: 'com.example.fitPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSfy8vE21FozMJOx5Hwx7ajbihVe526RI',
    appId: '1:411581975774:ios:19438bb30e765bf8a5064f',
    messagingSenderId: '411581975774',
    projectId: 'fit-pro-37183',
    storageBucket: 'fit-pro-37183.appspot.com',
    iosBundleId: 'com.example.fitPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlLG9k4gj_QSNiYMBB7KZAK-jB2tUYFiE',
    appId: '1:411581975774:web:0834a31f0c395cfba5064f',
    messagingSenderId: '411581975774',
    projectId: 'fit-pro-37183',
    authDomain: 'fit-pro-37183.firebaseapp.com',
    storageBucket: 'fit-pro-37183.appspot.com',
    measurementId: 'G-H89H134TS9',
  );
}
